# Core module
commands:
  rpengine: true
  card: true
  cardset: true
  cardselect: true
  colorlist: true

# Chat module
# TODO: test ranges
chat:
  enabled: true
  birdSpeed: 20 # blocks per second
  defaultChannel: rp

  channels:
    rp:
      range: 35
      permission: rpengine.chat.channel.rp
    ooc:
      prefix: '[OOC] '
      permission: rpengine.chat.channel.ooc
    whisper:
      range: 5
      prefix: '[whisper] '
    shout:
      range: 50
      prefix: '[SHOUT] '

  commands:
    channel: true
    whisper: true
    shout: true
    bird: true
