# Core module
commands:
  rpengine: true
  card: true
  cardset: true
  cardselect: true
  colorlist: true

# Chat module
chat:
  enabled: true
  whisperRange: 5
  shoutRange: 50
  birdSpeed: 20 # blocks per second
  defaultChannel: rp

  channels:
    rp:
      enabled: true
      range: 35
    ooc:
      enabled: true
      prefix: '[OOC]'

  commands:
    channel: true
