# Core module
commands:
  rpengine: true
  card: true
  cardset: true
  cardselect: true
  colorlist: true

# Chat module
chat:
  enabled: true
  whisperRange: 5
  shoutRange: 50
  birdSpeed: 20 # blocks per second
  defaultChannel: rp

  channels:
    rp:
      range: 35
      permission: rpengine.chat.channel.rp
      prefix: '[RP] '
    ooc:
      prefix: '[OOC] '
      permission: rpengine.chat.channel.ooc

  commands:
    channel: true
