# Core module
commands:
  rpengine: true
  card: true
  cardset: true
  cardselect: true
  colorlist: true

# Chat module
# TODO: test ranges
chat:
  enabled: true
  birdSpeed: 20 # blocks per second
  defaultChannel: rp

  countdown:
    range: 35
    color: DARK_RED
    sound: 'minecraft:ui.button.click'
    volume: 0.5
    pitch: 1
    goColor: DARK_GREEN
    goSound: 'minecraft:block.bell.use'
    goVolume: 0.5
    goPitch: 1

  roll:
    range: 35
    prefix: '[Roll] '

  channels:
    rp:
      range: 35
      permission: rpengine.chat.channel.rp
    ooc:
      prefix: '[OOC] '
      permission: rpengine.chat.channel.ooc
    whisper:
      range: 5
      prefix: '[whisper] '
    shout:
      range: 50
      prefix: '[SHOUT] '

  commands:
    channel: true
    whisper: true
    shout: true
    bird: true
    rp: true
    ooc: true
    toggleooc: true
    roll: true
    countdown: true
