# == Core module ==
commands:
  rpengine:
    enabled: true
  card:
    enabled: true
  cardset:
    enabled: true
    cooldown: 15
  cardselect:
    enabled: true
    cooldown: 15
  inspect:
    enabled: true
  colorlist:
    enabled: true
  playeractionmenu:
    enabled: true
  countdown:
    enabled: true

inspectRange: 35

# Start a countdown in the center of surrounding player's screens
countdown:
  range: 35
  color: YELLOW
  sound: 'minecraft:block.note_block.bit'
  volume: 0.5
  pitch: 1
  goColor: DARK_GREEN
  goSound: 'minecraft:block.note_block.bit'
  goVolume: 1
  goPitch: 2

# == Chat module ==
chat:
  enabled: true
  birdSpeed: 20       # Blocks per second
  actionMenu: true    # Brings up an action menu when you click on a players name in chat
  defaultChannel: rp

  # Generate a random number in a range
  roll:
    range: 35
    prefix: '[Roll] '

  channels:
    rp:
      range: 35
      permission: rpengine.chat.channel.rp
    ooc:
      prefix: '[OOC] '
      permission: rpengine.chat.channel.ooc
    whisper:
      messageColor: BLUE
      range: 5
      prefix: '[whisper] '
    shout:
      messageColor: RED
      range: 50
      prefix: '[SHOUT] '

  commands:
    channel:
      enabled: true
    whisper:
      enabled: true
    shout:
      enabled: true
    bird:
      enabled: true
    rp:
      enabled: true
    ooc:
      enabled: true
    toggleooc:
      enabled: true
    roll:
      enabled: true

# == Duel module ==
duels:
  enabled: true
  startRange: 35
  maxSecs: 300
  inviteExpireSecs: 60

  commands:
    duelrules:
      enabled: true
    duel:
      enabled: true
