# == Core module ==
commands:
  rpengine:
    enabled: true
  card:
    enabled: true
  cardset:
    enabled: true
    cooldown: 15
  cardselect:
    enabled: true
    cooldown: 15
  inspect:
    enabled: true
  colorlist:
    enabled: true

inspectRange: 35

# == Chat module ==
chat:
  enabled: true
  birdSpeed: 20 # blocks per second
  defaultChannel: rp

  countdown:
    range: 35
    color: DARK_RED
    sound: 'minecraft:ui.button.click'
    volume: 0.5
    pitch: 1
    goColor: DARK_GREEN
    goSound: 'minecraft:block.bell.use'
    goVolume: 0.5
    goPitch: 1

  roll:
    range: 35
    prefix: '[Roll] '

  channels:
    rp:
      range: 35
      permission: rpengine.chat.channel.rp
    ooc:
      prefix: '[OOC] '
      permission: rpengine.chat.channel.ooc
    whisper:
      range: 5
      prefix: '[whisper] '
    shout:
      range: 50
      prefix: '[SHOUT] '

  commands:
    channel:
      enabled: true
    whisper:
      enabled: true
    shout:
      enabled: true
    bird:
      enabled: true
    rp:
      enabled: true
    ooc:
      enabled: true
    toggleooc:
      enabled: true
    roll:
      enabled: true
    countdown:
      enabled: true
