name: RPEngine2
version: @version@
main: tv.twitch.moonmoon.rpengine2.RpEngine2
api-version: 1.13
authors: [Kasvot]
description: RPEngine rewrite
commands:
  rpengine:
    description: Root command for RPEngine2
    permission: rpengine.admin
    usage: /rpengine help
  card:
    description: Display RP character card
    usage: /card
    permission: rpengine.card
  cardset:
    description: Sets a card attribute
    usage: /cardset help
    permission: rpengine.cardset
