name: RPEngine2
version: @version@
main: tv.twitch.moonmoon.rpengine2.RpEngine2
api-version: 1.13
authors: [Kasvot]
description: RPEngine rewrite
load: STARTUP
softdepend: [ProtocolLib]
commands:
  rpengine:
    description: Admin command for RPEngine2
    permission: rpengine.admin
    usage: /rpengine help
  card:
    description: Display RP character card
    usage: /card
    permission: rpengine.card
  cardset:
    description: Sets a card attribute
    usage: /cardset help
    permission: rpengine.cardset
  cardselect:
    description: Lists options for a select
    usage: /cardselect help
    permission: rpengine.cardselect
  colorlist:
    description: Lists available colors
    usage: /colorlist
    permission: rpengine.colorlist
  channel:
    description: Channel management command
    usage: /channel help
    permission: rpengine.channel
  whisper:
    description: Speak softly and carry a big stick
    usage: /whisper <message>
    permission: rpengine.whisper
    aliases: [w]
  shout:
    description: Et tu brute
    usage: /shout <message>
    permission: rpengine.shout
    aliases: [yell]
  bird:
    description: A delayed message determined by the distance between players
    usage: /bird <player> <message>
    permission: rpengine.bird
  ooc:
    description: Alias for /channel join ooc (legacy)
    usage: /ooc
    permission: rpengine.ooc
  rp:
    description: Alias for /channel join rp (legacy)
    usage: /rp
    permission: rpengine.rp
  toggleooc:
    description: Alias for /channel mute ooc (legacy)
    usage: /toggleooc
    permission: rpengine.toggleooc
  roll:
    description: Generates a random number
    usage: /roll [max | min [max]]
    permission: rpengine.roll
  countdown:
    description: Starts a countdown for players
    usage: /countdown [seconds]
    permission: rpengine.countdown
