name: RPEngine2
version: '2.0'
main: tv.twitch.moonmoon.rpengine2.spigot.RpEngine2
api-version: '1.13'
authors: [Kasvot]
description: RPEngine rewrite
load: STARTUP
softdepend: [ProtocolLib, NametagEdit, Holograms]
commands:
  rpengine:
    description: Admin command for RPEngine2
    permission: rpengine.admin
    usage: /rpengine help
  card:
    description: Display RP character card
    permission: rpengine.card
    usage: /card
  cardset:
    description: Sets a card attribute
    usage: /cardset help
    permission: rpengine.cardset
  cardselect:
    description: Lists options for a select
    usage: /cardselect help
    permission: rpengine.cardselect
  inspect:
    description: Allows you to view other players cards
    usage: /inspect <player>
    permission: rpengine.inspect
  colorlist:
    description: Lists available colors
    usage: /colorlist
    permission: rpengine.colorlist
  playeractionmenu:
    description: Displays the player action menu (internal)
    usage: /playeractionmenu <player>
    permission: rpengine.playeractionmenu
  countdown:
    description: Starts a countdown for nearby players
    usage: /countdown [seconds]
    permission: rpengine.countdown
  roll:
    description: Generates a random number
    usage: /roll [max | min [max]]
    permission: rpengine.roll
    aliases: [rand, rnd]
  played:
    description: Prints play time on server
    usage: /played
    permission: rpengine.played
  channel:
    description: Channel management command (join, mute, etc.)
    usage: /channel help
    permission: rpengine.chat.channel
  whisper:
    description: Speak softly and carry a big stick
    usage: /whisper <message>
    permission: rpengine.chat.whisper
    aliases: [w]
  shout:
    description: Et tu brute
    usage: /shout <message>
    permission: rpengine.chat.shout
    aliases: [yell]
  bird:
    description: A delayed message determined by the distance between players
    usage: /bird <player> <message>
    permission: rpengine.chat.bird
  ooc:
    description: Alias for /channel join ooc (legacy)
    usage: /ooc
    permission: rpengine.chat.ooc
  rp:
    description: Alias for /channel join rp (legacy)
    usage: /rp
    permission: rpengine.chat.rp
  toggleooc:
    description: Alias for /channel mute ooc (legacy)
    usage: /toggleooc
    permission: rpengine.chat.toggleooc
  emote:
    description: You feel as though...
    usage: /emote <phrase>
    aliases: [em, me]
    permission: rpengine.chat.emote
  duelrules:
    description: Prints the duel rules
    usage: /duelrules
    aliases: [drules]
    permission: rpengine.duels.duelrules
  duel:
    description: Challenges a player to duel or accepts an active challenge
    usage: /duel <player>
    permission: rpengine.duels.duel
  dueldecline:
    description: Declines a duel challenge
    usage: /dueldecline <player>
    permission: rpengine.duels.dueldecline
    aliases: [ddecline]
  forfeit:
    description: Forfeits an active duel
    usage: /forfeit
    aliases: [yield, concede]
    permission: rpengine.duels.forfeit
